# Visit https://goreleaser.com for documentation on how to customize this behavior
builds:
  - binary: iup
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X gitlab.ct.activision.com/ct/infrastructure/symserver/pkg/common.appVersion={{.Version}}"
    goos:
      - linux
    goarch:
      - amd64

dockers:
  - id: linux_amd64
    image_templates:
      - "{{.Env.IMAGENAME}}:{{.Tag}}"
    build_flag_templates:
      - --label=org.opencontainers.image.created={{.Now.Format "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.authors="Adrian Astley"
      - --label=org.opencontainers.image.url={{.GitURL}}
      - --label=org.opencontainers.image.documentation={{.GitURL}}/README.md
      - --label=org.opencontainers.image.source={{.GitURL}}
      - --label=org.opencontainers.image.version={{.Tag}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.licenses="Apache 2.0"
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.description="This docker container acts as a proxy for IotaWatt uploads to VictoriaMetrics via Influx V1 line protocol"
    use: docker

changelog:
  skip: false
